return {
  -- this table overrides highlights in all themes
  Normal = { bg = "#0f0f0f" },
  ["@none"] = { fg = "#dedede" },
  ["@punctuation"] = { fg = "#d3d2c2" },
  ["@punctuation.special"] = { fg = "#3e7fe1" },
  --
  ["@keyword"] = { fg = "#5d8fdb" },
  ["@include"] = { link = "@keyword" },
  ["@type.qualifier"] = { link = "@keyword" },
  ["@constant.builtin"] = { link = "@keyword" },
  ["@namespace"] = { link = "@keyword" },
  ["@conditional"] = { link = "Conditional" },
  ["@keyword.return"] = { link = "@conditional" },
  ["@repeat"] = { link = "@conditional" },
  --
  ["@function"] = { fg = "#d5c96e" },
  ["@lsp.type.function"] = { link = "@function" },
  ["@method"] = { link = "@function" },
  Conditional = { fg = "#c47cca" },
  Structure = { link = "@type" },
  Type = { link = "@type" },
  Attribute = { fg = "#ba6cee" },
  Comment = { fg = "#a4a4a4" },
  BuiltinType = { fg = "#f1d65d" },
  --
  ["@type"] = { fg = "#92d15f" },
  ["@type.builtin"] = { link = "@keyword" },
  ["@lsp.type.namespace"] = { fg = "#2461bd" },
  ["@lsp.type.enum"] = { fg = "#4EC9B0" },
  ["@lsp.type.enumMember"] = { fg = "#bee06d" },
  --
  ["@string"] = { fg = "#d4ad52" },
  ["@string.escape"] = { fg = "#3e7fe1" },
  ["@number"] = { fg = "#d0cc56" },
  ["@boolean"] = { fg = "#5388c0" },
  --
  ["@tag"] = { link = "@keyword" },
  ["@tag.attribute"] = { fg = "#81d6e6", italic = true }, -- Tags like html tag names.
  ["@tag.delimiter"] = { link = "@punctuation" },
  --
  ["@parameter"] = { fg = "#81d6e6" },
  ["@variable"] = { fg = "#81d6e6" },
  ["@lsp.typemod.variable.readonly"] = { link = "@variable" },
  ["@lsp.typemod.variable.defaultLibrary"] = { fg = "#c76f7a" },
  --
  ["@attribute"] = { link = "Attribute" },
  ["@field"] = { fg = "#cfc682" },
  ["@property"] = { link = "@field" },
  ["@tag.attribute.tsx"] = { link = "@field", italic = true },
  --
  ["rustAttribute"] = { link = "Attribute" },
  ["@lsp.type.decorator.rust"] = { link = "rustAttribute" },
  ["rustDeriveTrait"] = { link = "rustAttribute" },
  ["@lsp.type.derive.rust"] = { link = "rustAttribute" },
  ["@lsp.type.variable.rust"] = { fg = "#81d6e6" },
  ["@lsp.mod.unsafe.rust"] = { fg = "#da7777" },
  ["@lsp.mod.controlFlow.rust"] = { fg = "#c47cca" },
  ["@lsp.typemod.function.unsafe.rust"] = { link = "@lsp.mod.unsafe.rust" },
  ["@lsp.type.method.rust"] = { fg = "#d5c96e" },
  ["@lsp.typemod.method.rust"] = { link = "@lsp.type.method.rust" },
  ["@lsp.typemod.function.defaultLibrary.rust"] = { link = "@lsp.type.method.rust" },
  ["@lsp.typemod.method.defaultLibrary.rust"] = { link = "@lsp.type.method.rust" },
  ["@lsp.typemod.method.reference.rust"] = { link = "@lsp.type.method.rust" },
  ["@lsp.typemod.method.trait.rust"] = { link = "@lsp.type.method.rust" },
  ["rustSigil"] = { link = "@punctuation" },
  ["@lsp.type.interface.rust"] = { fg = "#4EC980", italic = true },
  ["@lsp.type.keyword.rust"] = { fg = "#5d8fdb" },
  ["@lsp.type.number.rust"] = { fg = "#d0cc56" },
  ["@lsp.type.macro.rust"] = { link = "rustAttribute" },
  ["@lsp.type.lifetime.rust"] = { fg = "#de77e7" },
  ["@lsp.type.selfKeyword.rust"] = { fg = "#de77e7" },
  ["@lsp.type.builtinType.rust"] = { link = "BuiltinType" },
  ["@lsp.type.parameter.rust"] = { fg = "#81d6e6" },
  ["@lsp.type.typeAlias.rust"] = { link = "@type" },
  ["@lsp.type.typeParameter.rust"] = { link = "@type" },
  ["@lsp.typemod.typeAlias.trait.modrust"] = { link = "@type" },
  ["@lsp.typemod.typeAlias.library.modrust"] = { link = "@type" },
  ["@lsp.typemod.typeAlias.defaultLibrary.modrust"] = { link = "@type" },
  ["@lsp.mod.mutable.rust"] = { bold = true },
  -- ruby
  -- ["@spell.ruby"] = { link = "Attribute" },
  ["@comment.ruby"] = { link = "Comment" },
  ["@string.ruby"] = { link = "@string" },
  ["@keyword.function.ruby"] = { link = "@keyword" },
  ["@conditional.ruby"] = { link = "Conditional" },
  -- ["@boolean.ruby"] = { link = "BuiltinType" },
}
