return {
  -- this table overrides highlights in all themes
  Normal                = { bg = "#0d0d0d" },
  ["@string"]           = { fg = "#d4ad52" },
  ["@string.escape"]    = { fg = "#2165d1" },
  ["@type"]             = { fg = "#92d15f" },
  ["@attribute"]        = { fg = "#ba6cee" },
  ["@operator"]         = { fg = "#d3d2c2" },
  ["@number"]           = { fg = "#d0cc56" },
  ["@boolean"]          = { fg = "#5388c0" },
  ["@keyword.return"]   = { fg = "#bf8bba" },
  ["@conditional"]      = { fg = "#bf8bba" },
  ["@repeat"]           = { fg = "#bf8bba" },
  ["@type.qualifier"]   = { fg = "#5d85db" },
  ["@parameter"]        = { fg = "#81d6e6", style = "bold" },
  ["@variable"]         = { fg = "#81d6e6" },
  ["@constant.builtin"] = { fg = "#5d85db" },
  ["@namespace"]        = { fg = "#4c7cec" },
  ["@tag"]              = { fg = "#4c7cec" },
  ["@tag.attribute"]    = { fg = "#81d6e6", style = "italic" }, -- Tags like html tag names.
  ["@tag.delimiter"]    = { fg = "#d3d2c2" },
  ["@field"]            = { fg = "#d5c96e" },
  ["@property"]         = { link = "@field" },
  ["@include"]          = { fg = "#5d8fdb" },
  ["@keyword"]          = { fg = "#5d8fdb" },
  ["@function"]         = { fg = "#d5c96e" },
  ["@method"]           = { fg = "#d5c96e" },
}
